### ISSUE TITLE
Example Use Case

### ISSUE THREAD

**Issue by oliverdunk** [an1m3b1tch3z/lolidipper#1]
How to compile and run the script?

**Comment by stugmi** [comment]
Like any C program

**Comment by oliverdunk** [comment]
As in, do I put it on a MultiCraft server and run in a jar, or just run it under a low privelidge SSH account.

**Comment by stugmi** [comment]
Find out yourself, i'm not your mum.

**Comment by notlemmon** [comment]
ur a spastic
